### PR TITLE
Move `ext-phalcon` to require-dev

### PR DESCRIPTION
**Pull request by thinhvoxuan**
Phalcon is required for this package. I absolutely agree with that. But we do not have to require another package `ext-phalcon` for checking Phalcon is install in this env or not. 

Btw, my problem is I docker my source code with Phalcon image but composer run by another image that not have Phalcon installed. So I have to move that ext-phalcon to require-dev

### CODE REVIEW

**Comment by sergeyklay** [comment]
Why

**Comment by thinhvoxuan** [comment]
I add some modify that could check multi AuthMiddleware Anotations

**Comment by SidRoberts** [comment]
Hi, could you fix the PSR2 errors?:

```
$ vendor/bin/phpcs src/ --standard=psr2

FILE: ...ome/travis/build/SidRoberts/phalcon-authmiddleware/src/Event.php
----------------------------------------------------------------------
FOUND 10 ERRORS AFFECTING 8 LINES
----------------------------------------------------------------------
 35 | ERROR | [x] Line indented incorrectly; expected at least 12
    |       |     spaces, found 10
 36 | ERROR | [x] Line indented incorrectly; expected at least 12
    |       |     spaces, found 10
 37 | ERROR | [x] Line indented incorrectly; expected 12 spaces,
    |       |     found 10
 38 | ERROR | [x] Line indented incorrectly; expected at least 16
    |       |     spaces, found 14
 39 | ERROR | [x] Line indented incorrectly; expected 12 spaces,
    |       |     found 10
 40 | ERROR | [x] Line indented incorrectly; expected 12 spaces,
    |       |     found 10
 40 | ERROR | [x] Expected 0 spaces after opening bracket; 1 found
 40 | ERROR | [x] Expected 0 spaces before closing bracket; 1 found
 41 | ERROR | [x] Line indented incorrectly; expected at least 16
    |       |     spaces, found 12
 42 | ERROR | [x] Line indented incorrectly; expected 12 spaces,
    |       |     found 10
----------------------------------------------------------------------
PHPCBF CAN FIX THE 10 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 63ms; Memory: 6Mb
```

**Comment by thinhvoxuan** [comment]
@SidRoberts I did it after 2 days. 
Again with why I move `ext-phalcon` to `require-dev` but not `require` in composer. The real reason is in `src` folder, you do not use any class of `ext-phalcon`, fact that all testcase passed.

**Comment by thinhvoxuan** [comment]
@SidRoberts I add case that we have more than one Middleware in check before pass it to Controller

**Comment by SidRoberts** [comment]
I've found a solution to requiring Phalcon as a dependency: http://stackoverflow.com/a/26547261 . Can you revert composer.json and I'll merge the rest?

**Comment by thinhvoxuan** [comment]
@SidRoberts Done. Have a nice day.

**Comment by SidRoberts** [comment]
Thanks. :)

**Pull request merged**
